#!/bin/bash

set -eu

METRICS_FILE="/var/lib/node_exporter/textfile_collector/vero-metrics.prom"
TMP_FILE="${METRICS_FILE}.tmp"
PREFIX="vero_"

# remove existing files
rm -f "${TMP_FILE}"

# get temperatures
{
  echo "# HELP ${PREFIX}temperature Temperatures of the components in degree celsius.";
  echo "# TYPE ${PREFIX}temperature gauge";
} >> "${TMP_FILE}"
for SENSOR in /sys/class/thermal/thermal_*; do
  SENSOR=$(basename $SENSOR)
  unset CPU_TEMP_CELSIUS
  unset CPU_TEMP_TYPE

  CPU_TEMP_CELSIUS="$(awk '{printf "%.3f", $1/1000}' /sys/class/thermal/${SENSOR}/temp)" || true
  CPU_TEMP_CELSIUS="${CPU_TEMP_CELSIUS:=0}"
  CPU_TEMP_TYPE="$(cat /sys/class/thermal/${SENSOR}/type)"
  CPU_TEMP_TYPE="${CPU_TEMP_TYPE:=N/A}"

  echo "${PREFIX}temperature{sensor=\"${SENSOR}\",type=\"${CPU_TEMP_TYPE}\"} ${CPU_TEMP_CELSIUS}" >> "${TMP_FILE}"
done

# write metrics file
mv "${TMP_FILE}" "${METRICS_FILE}"

exit 0
